[package]
name = "sa-token-plugin-ntex-v212"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Ntex 2.12.x bindings for sa-token-rust"

[dependencies]
sa-token-plugin-common = { workspace = true }
sa-token-core = { workspace = true }
sa-token-adapter = { workspace = true }
sa-token-macro = { workspace = true }

sa-token-storage-memory = { workspace = true, optional = true }
sa-token-storage-redis = { workspace = true, optional = true }
sa-token-storage-database = { workspace = true, optional = true }

async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
http = { workspace = true }
ntex = "2.18.0"
urlencoding = { workspace = true }
tracing = { workspace = true }

[features]
default = ["memory"]
memory = ["dep:sa-token-storage-memory"]
redis = ["dep:sa-token-storage-redis"]
database = ["dep:sa-token-storage-database"]
full = ["memory", "redis", "database"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true
